version: 2.1
orbs:
  node: circleci/node@4.2.0
jobs:
  install-and-lint:
    executor:
      name: node/default
    steps:
      - checkout
      - run: yarn --ignore-engines
      - run: yarn lint
workflows:
  install-and-lint:
    jobs:
      - install-and-lint
